set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(RELATIVE_SYSROOT_PATH sysroots/core2-32-poky-linux)
set(RELATIVE_COMPILER_PATH sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux)
set(CROSS_COMPILE i586-poky-linux-)

set(COMPILER_PREFIX "${TOOLCHAIN_PATH}/${RELATIVE_COMPILER_PATH}/${CROSS_COMPILE}")

set(EDISON_C_COMPILER "${COMPILER_PREFIX}gcc")
set(EDISON_CXX_COMPILER "${COMPILER_PREFIX}g++")

set(EDISON_SYSROOT_PATH "${TOOLCHAIN_PATH}/${RELATIVE_SYSROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH "${EDISON_SYSROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

set(CMAKE_SYSROOT "${EDISON_SYSROOT_PATH}")

set(COMMON_C_FLAGS "-m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -mstackrealign -fno-omit-frame-pointer")
set(COMMON_C_FLAGS "${COMMON_C_FLAGS} -O2 -pipe -g -feliminate-unused-debug-types")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${COMMON_C_FLAGS} --sysroot=${EDISON_SYSROOT_PATH}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_C_FLAGS} --sysroot=${EDISON_SYSROOT_PATH}")

set(COMMON_LD_FLAGS "-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed --sysroot=${EDISON_SYSROOT_PATH}")

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${COMMON_LD_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${COMMON_LD_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${COMMON_LD_FLAGS}")
